/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codewhisperer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    //In Java You are given a 2D matrix of dimension and a positive integer. You have to rotate the matrix a give number of times and print the resulting matrix. Rotation of the matrix should be in anti-clockwise direction.
    public static void rotateMatrix(int[][] matrix, int n) {
        int layer = 0;
        while (layer < n / 2) {
            int first = layer;
            int last = n - 1 - layer;
            for (int i = first; i < last; i++) {
                int offset = i - first;
                int top = matrix[first][i];
                matrix[first][i] = matrix[last - offset][first];
                matrix[last - offset][first] = matrix[last][last - offset];
                matrix[last][last - offset] = matrix[i][last];
                matrix[i][last] = top;
            }
            layer++;
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int[][] matrix = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};
        printMatrix(matrix);
        rotateMatrix(matrix, 3);
        printMatrix(matrix);
        System.out.println();
    }

    public static void printMatrix(int[][] matrix) {
        for (int i = 0; i < matrix.length; i++) {
            for (int j = 0; j < matrix[i].length; j++) {
                System.out.print(matrix[i][j] + " ");
            }
            System.out.println();
        }
    }
    
}
